/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kodeir_jcore_natives_HelloNative */

#ifndef _Included_com_kodeir_jcore_natives_HelloNative
#define _Included_com_kodeir_jcore_natives_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kodeir_jcore_natives_HelloNative
 * Method:    displayHelloNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kodeir_jcore_natives_HelloNative_displayHelloNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
